### ISSUE TITLE
数据库初始化脚本没有，还得自己建表啊

### ISSUE THREAD

**Issue by lihuazhang** [hustcc/iOS-private-api-checker#1]
数据库初始化脚本没有，还得自己建表啊

**Comment by lihuazhang** [comment]
找到了。注释掉了。。

**Comment by lihuazhang** [comment]
```bash
➜  iOS-private-api-checker git:(master) ✗ python build_api_db.py
table framework_dump_apis already exists
table framework_header_apis already exists
table document_apis already exists
table undocument_apis already exists
table private_apis already exists
table private_framework_dump_apis already exists
table framework_private_apis already exists
None
no such table: ZTOKEN
Traceback (most recent call last):
  File "build_api_db.py", line 98, in <module>
    print rebuild_document_api('9.1', 'docSet.dsidx')
  File "build_api_db.py", line 18, in rebuild_document_api
    document_apis = api_utils.document_apis(sdk, docset)
  File "/Users/lihuazhang/code/iOS-private-api-checker/api/api_utils.py", line 78, in document_apis
    for api in apiset:
TypeError: 'bool' object is not iterable

```

**Comment by hustcc** [comment]
难道是不同版本sdk结构不一样…可以将9.1发给我吗？wzwahl36#qq.com感谢…

**Comment by lihuazhang** [comment]
在segment里回复过你了。。
