### ISSUE TITLE
执行python build_api_db.py , 报错

### ISSUE THREAD

**Issue by veryitman** [hustcc/iOS-private-api-checker#12]
执行python build_api_db.py 
报错:
Traceback (most recent call last):
  File "build_api_db.py", line 157, in <module>
    rebuild_sdk_private_api(sdk_version, False)
  File "build_api_db.py", line 135, in rebuild_sdk_private_api
    print rebuild_dump_framework_api(sdk_version['sdk'], sdk_version['framework'])
  File "build_api_db.py", line 55, in rebuild_dump_framework_api
    framework_dump_header_apis = api_utils.framework_dump_apis(sdk, framework_folder)
  File "/Users/mark/developer/tools/iOSTools/iOS-private-api-checker/api/api_utils.py", line 25, in framework_dump_apis
    all_headers = _get_headers_from_path(framework_header_folder)
  File "/Users/mark/developer/tools/iOSTools/iOS-private-api-checker/api/api_utils.py", line 127, in _get_headers_from_path
    frameworks = os.listdir(framework_folder)
OSError: [Errno 2] No such file or directory: '/Users/mark/developer/tools/iOSTools/iOS-private-api-checker/tmp/pub-headers'

**Comment by hustcc** [comment]
错误的问题已经在最后一行给出了，目录找不到，创建`tmp`目录即可。

**Comment by veryitman** [comment]
tmp 目录是存在的.

**Comment by veryitman** [comment]
大神, 请问:
我看 excel 导出的结果是这样的:
   架构         证书类型           Warnings数    Errors数     私有API    XcodeGhost
  armv7    Ad Hoc/Developer           2           1                 1 / 0            安全
私有 api 1/0是什么意思啊?
还有 errors 数, 怎么才可以看到具体的 error?

**Comment by hustcc** [comment]
excel是一个多tab页的。点后面的tab页就可以看到error的详细信息。

**Comment by veryitman** [comment]
非常感谢!
