### ISSUE TITLE
第一种方式直接运行py, 报错

### ISSUE THREAD

**Issue by veryitman** [hustcc/iOS-private-api-checker#3]
Traceback (most recent call last):
  File "iOS_private.py", line 13, in <module>
    from app.utils import checkipa
  File "/Users/mark/developer/tools/iOSTools/iOS-private-api-checker/app/__init__.py", line 7, in <module>
    from flask import Flask
ImportError: No module named flask

**Comment by hustcc** [comment]
请安装requirement文件中的py库~

**Comment by veryitman** [comment]
安装这个库了.
新的问题:https://github.com/hustcc/iOS-private-api-checker/issues/11
